---
  ###
  ###
  # CONFIGURE FIREWALL:
  # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
  # https://www.weave.works/docs/net/latest/faq/
  ###
  ###
  - name: Install UFW
    apt:
      name:
      - ufw
      state: present
      autoclean: yes

  - name: Start and enable UFW service
    systemd:
      name: ufw
      state: started
      enabled: yes

  - name: Check if UFW original config file exists?
    stat:
      path: /etc/default/ufw.orig
    register: ufw_conf_exists

  - name: Make a backup of UFW config file if original config file not exists
    copy:
      remote_src: yes
      src: /etc/default/ufw
      dest: /etc/default/ufw.orig
      force: no
    when: ufw_conf_exists.stat.exists == false

  - name: Disable IPv6
    replace:
      path: /etc/default/ufw
      regexp: "IPV6.*"
      replace: "IPV6=no"
    when: ipv6_enabled == false

  - name: Enable IPv6
    replace:
      path: /etc/default/ufw
      regexp: "IPV6.*"
      replace: "IPV6=yes"
    when: ipv6_enabled == true

  - name: Set logging
    community.general.ufw:
      logging: 'low'

  - name: Allow all outgoing connections
    community.general.ufw:
      direction: outgoing
      default: allow

  - name: Deny all incoming connections
    community.general.ufw:
      direction: incoming
      default: deny

  - name: Allow SSH
    community.general.ufw:
      rule: allow
      port: ssh
      proto: tcp

  - name: Allow inbound port of {{ kubernetes_api_server_port }} for master node
    community.general.ufw:
      rule: allow
      port: "{{ kubernetes_api_server_port | string }}"
      proto: tcp
      comment: Kubernetes API Server
    when: "ansible_hosts_for_k8s_master in group_names"

  - name: Allow inbound ports of 30000-32767/tcp for worker node(s)
    community.general.ufw:
      rule: allow
      port: 30000:32767
      proto: tcp
      comment: Kubernetes NodePort Services
    when: "ansible_hosts_for_k8s_worker in group_names"

  - name: Allow inbound ports of 30000-32767/udp for worker node(s)
    community.general.ufw:
      rule: allow
      port: 30000:32767
      proto: udp
      comment: Kubernetes NodePort Services
    when: "ansible_hosts_for_k8s_worker in group_names"

  - name: Configure TCP Ports for Weave Net
    community.general.ufw:
      rule: allow
      port: '6783'
      proto: tcp
      comment: Weave Net

  - name: Configure UDP Ports for Weave Net
    community.general.ufw:
      rule: allow
      port: 6783:6784
      proto: udp
      comment: Weave Net

  - name: Enable UFW
    community.general.ufw:
      state: enabled
