---
  ###
  ###
  # CREATE PRIVILEGE USER FOR KUBERNETES CLUSTER
  ###
  ###
  - name: Create group {{ kubernetes_group }} to manage Kubernetes Cluster
    group:
      name: "{{ kubernetes_group }}"
      state: present

  - name: Create user {{ kubernetes_user }} to manage Kubernetes Cluster
    user:
      name: "{{ kubernetes_user }}"
      append: yes
      comment: Kubernetes
      groups: sudo, {{ kubernetes_group }}
      password: '*'
      expires: -1
      home: /home/{{ kubernetes_user }}
      shell: /bin/bash
      state: present

  - name: Set sudo for {{ kubernetes_user }}
    copy:
      dest: /etc/sudoers.d/{{ kubernetes_user }}
      content: '{{ kubernetes_user }} ALL=(ALL) NOPASSWD: ALL'
      owner: root
      group: root
      mode: '0440'
      validate: /sbin/visudo -csf %s
