---
  ###
  ###
  # GET NODES STATUS
  ###
  ###
  - name: Waiting for node(s) to get ready...
    pause:
      seconds: 45

  - name: Get node(s) status
    become: yes
    become_user: "{{ kubernetes_user }}"
    shell: kubectl get nodes
    register: kubectl_get_nodes

  - name: Verify node(s) status
    debug: msg="{{ kubectl_get_nodes.stdout_lines }}"
