---
  ###
  ###
  # UPDATE KUBERNETES WORKER
  ###
  ###
  - name: Get Worker node
    become: yes
    become_user: "{{ kubernetes_user_for_k8s_master }}"
    shell: kubectl get nodes -o wide | grep {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }} | awk '{print $1}'
    register: worker_node
    delegate_to: "{{ groups[inventory_group_for_master_node][0] }}"

#  - name: Get Worker node register
#    debug: msg="{{ worker_node.stdout }}"

  - name: Drain Worker node
    become: yes
    become_user: "{{ kubernetes_user_for_k8s_master }}"
    shell: kubectl drain {{ worker_node.stdout }} --ignore-daemonsets
    delegate_to: "{{ groups[inventory_group_for_master_node][0] }}"


  - name: apt-mark unhold kubeadm
    dpkg_selections:
      name: kubeadm
      selection: install

  - name: Update kubeadm
    apt:
      name: kubeadm={{ version_to_upgrade }}
      state: present
      update_cache: yes
      autoclean: yes

  - name: apt-mark hold kubeadm
    dpkg_selections:
      name: kubeadm
      selection: hold

  - name: Get kubeadm version
    shell: "kubeadm version -o short"
    register: kubeadm_version

  - name: Verify kubeadm version
    debug: msg="{{ kubeadm_version.stdout }}"


  - name: Set node config
    shell: kubeadm upgrade node >> node_updated_`date +'%y%m%d-%H%M%S'`.txt
    args:
      chdir: $HOME


  - name: apt-mark unhold kubectl
    dpkg_selections:
      name: kubectl
      selection: install

  - name: Update kubectl
    apt:
      name: kubectl={{ version_to_upgrade }}
      state: present
      force: yes
      update_cache: yes
      autoclean: yes

  - name: apt-mark hold kubectl
    dpkg_selections:
      name: kubectl
      selection: hold

  - name: Get kubectl version
    shell: "kubectl version --short --client"
    register: kubectl_version

  - name: Verify kubectl version
    debug: msg="{{ kubectl_version.stdout }}"


  - name: apt-mark unhold kubelet
    dpkg_selections:
      name: kubelet
      selection: install

  - name: Update kubelet
    apt:
      name: kubelet={{ version_to_upgrade }}
      state: present
      update_cache: yes
      autoclean: yes

  - name: apt-mark hold kubelet
    dpkg_selections:
      name: kubelet
      selection: hold

  - name: Get kubelet version
    shell: "kubelet --version"
    register: kubelet_version

  - name: Verify kubelet version
    debug: msg="{{ kubelet_version.stdout }}"

  - name: Restart kubelet Service
    systemd:
      state: restarted
      name: kubelet
      enabled: yes


  - name: Waiting for kubelet to be ready"
    pause:
      seconds: 5

  - name: Uncordon Worker node
    become: yes
    become_user: "{{ kubernetes_user_for_k8s_master }}"
    shell: kubectl uncordon {{ worker_node.stdout }}
    delegate_to: "{{ groups[inventory_group_for_master_node][0] }}"


  - name: Get node(s) status
    become: yes
    become_user: "{{ kubernetes_user_for_k8s_master }}"
    shell: kubectl get nodes
    register: kubectl_get_nodes
    delegate_to: "{{ groups[inventory_group_for_master_node][0] }}"

  - name: Verify node(s) status
    debug: msg="{{ kubectl_get_nodes.stdout_lines }}"
    delegate_to: "{{ groups[inventory_group_for_master_node][0] }}"

  - name: Upgrade completed for {{ ansible_hostname }}
    pause:
      seconds: 10
