---
# defaults file for kubernetes-setup

# Linux user and group to manage Kubernetes Cluster
kubernetes_user: kubeusr     # This will create a privillege user without password. You can set the password for this user later.
kubernetes_group: kubeusr

# Is IPv6 enabled on all nodes?
ipv6_enabled: false

# Hosts firewall configuration
configure_firewall: true
kubernetes_api_server_port: 6443

# Ansible Inventory group for Master node and Workers nodes
ansible_hosts_for_k8s_master: k8s-master
ansible_hosts_for_k8s_worker: k8s-worker

# Kubernetes version and POD Network CIDR
# Latest Kubernetes version: https://github.com/kubernetes/kubernetes/releases
kubernetes_version: 1.20.7-00   # Have to be in the format of 1.XX.X-00
pod_network_cidr: 10.244.0.0/16

# Test deployment of NGINX with NodePort?
test_deployment: false
delete_deployment_after_testing: true
